spring:
  application:
    name: dual-ds-tx
  datasource:
    alpha:
      jdbc-url: jdbc:postgresql://localhost:5433/alpha
      username: alpha
      password: alpha
      hikari:
        pool-name: alpha-pool
        auto-commit: false
    omega:
      jdbc-url: jdbc:postgresql://localhost:5444/omega
      username: omega
      password: omega
      hikari:
        pool-name: omega-pool
        auto-commit: false
management:
  server:
    port: 8081
  security:
    enabled: false
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus, env, configprops, beans
    jmx:
      exposure:
        include: info, health, metrics, prometheus, env, configprops, beans
  endpoint:
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true
