spring:
  application:
    name: dual-ds-tx
  threads.virtual.enabled: true
  datasource:
    alpha:
      url: jdbc:postgresql://localhost:5433/alpha
      username: alpha
      password: alpha
      hikari:
        minimum-idle: 0
        idle-timeout: 10000
        maximum-pool-size: 1
        pool-name: alpha-pool
        auto-commit: false
    omega:
      url: jdbc:postgresql://localhost:5444/omega
      username: omega
      password: omega
      hikari:
        minimum-idle: 0
        idle-timeout: 10000
        maximum-pool-size: 1
        pool-name: omega-pool
        auto-commit: false
management:
  server:
    port: 8081
  security:
    enabled: false
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus, env, configprops, beans
    jmx:
      exposure:
        include: info, health, metrics, prometheus, env, configprops, beans
  endpoint:
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true
logging:
  level:
    com.zaxxer.hikari: WARN
    org.springframework.jdbc: DEBUG
    org.springframework.transaction: TRACE
    #org.springframework.transaction.interceptor: TRACE
